### ISSUE TITLE
用不了啊,大佬

### ISSUE THREAD

**Issue by phonet** [xiaomiwujiecao/taroWxParse#1]

**Comment by program-spiritual** [comment]
这个是个组件，直接使用组件的方式引用，不能当做页面的方式引用，如果有疑问 请加我的QQ  1410200695

**Comment by program-spiritual** [comment]
如果是组件数据问题 最好调试一下

**Comment by phonet** [comment]
嗯,已经找到taro官方的同样集成wxParse的组件使用,与你的这个差不多,感谢!
https://github.com/NervJS/taro-components-test/blob/master/src/pages/wxParse/wxParse.js
