### ISSUE TITLE
在h5下不支持吗？

### ISSUE THREAD

**Issue by cnscorpions** [xiaomiwujiecao/taroWxParse#5]

**Comment by program-spiritual** [comment]
![image](https://user-images.githubusercontent.com/8823477/79458758-dc372180-8024-11ea-8301-11f6d735dffb.png)
如图所示，我写的这个组件仅支持wxml ，wxss,如果你想要实现html5 上的应用，实际上有很多好用的插件 ，简单来说 例如像 v-html 这种指令本身就可以渲染富文本，如果你想找到符合多场景的工具，可以访问 https://github.com/jin-yufeng/Parser

**Comment by cnscorpions** [comment]
谢谢，已经在react中插入了html了
